// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfohZXxq4U1O-txn80Dz8pTMuqc1dNOdo',
    appId: '1:30161720251:web:0f4c5fbfbe063b2cfc2a9e',
    messagingSenderId: '30161720251',
    projectId: 'boxmatch-e2224',
    authDomain: 'boxmatch-e2224.firebaseapp.com',
    storageBucket: 'boxmatch-e2224.firebasestorage.app',
    measurementId: 'G-8MBDE00TVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjb61UZwddPIiJZAoojEUVlxtaYsH7RsU',
    appId: '1:30161720251:android:6a2dc59e0e86485bfc2a9e',
    messagingSenderId: '30161720251',
    projectId: 'boxmatch-e2224',
    storageBucket: 'boxmatch-e2224.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyP5kyfW-jtllwDDt0j3EUc-ejyibLs9w',
    appId: '1:30161720251:ios:a5563a52204e136ffc2a9e',
    messagingSenderId: '30161720251',
    projectId: 'boxmatch-e2224',
    storageBucket: 'boxmatch-e2224.firebasestorage.app',
    iosBundleId: 'com.example.boxmatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyP5kyfW-jtllwDDt0j3EUc-ejyibLs9w',
    appId: '1:30161720251:ios:a5563a52204e136ffc2a9e',
    messagingSenderId: '30161720251',
    projectId: 'boxmatch-e2224',
    storageBucket: 'boxmatch-e2224.firebasestorage.app',
    iosBundleId: 'com.example.boxmatch',
  );
}
